---
- name: Install Certbot and the Nginx plugin
  yum:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain Let's Encrypt certificate using Certbot
  shell: >
    certbot --nginx --non-interactive --agree-tos --redirect
    -d {{ domain }} -m {{ email }}
  notify:
    - reload nginx
